{% set name = "light-curve-python" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/light-curve/light_curve-{{ version }}.tar.gz
  sha256: 341ad9b6a461fb544bdcb84c783697427402aa6030a745e3714d40b735183265

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install .[full] -vv --no-deps --ignore-installed
  script_env:
    # Package cargo flags
    - MATURIN_PEP517_ARGS=--locked --no-default-features --features=ceres-system,fftw-system,gsl  # [not win]
    - MATURIN_PEP517_ARGS=--locked --no-default-features --features=fftw-system  # [win]
    # eigen3 discovery, a transitive dependency of ceres-solver
    - CPLUS_INCLUDE_PATH={{ PREFIX }}/include:{{ PREFIX }}/include/eigen3  # [not win]
    - INCLUDE={{ PREFIX }}\Library\include;{{ PREFIX }}\Library\include\eigen3  # [win]
    # fftw discovery
    - LIBRARY_PATH={{ PREFIX }}/lib  # [not win]
    - LIB={{ PREFIX }}\Library\lib  # [win]
    # Fix glog-related error when building ceres-solver
    # https://github.com/mhx/dwarfs/issues/201#issuecomment-1958068640
    - CXXFLAGS=-DGLOG_USE_GLOG_EXPORT
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - pkg-config
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
    - ceres-solver >=2.2,<2.3  # [not win]
    - fftw >=3.3,<3.4
    - gsl >=2.1,<3.0  # [not win]
    - libblas  # [linux]
  run:
    - python
    - numpy <3
    - iminuit >=2.21,<3
    - scipy >=1,<2

test:
  imports:
    - light_curve
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Feature extractor from noisy time series
  home: https://github.com/light-curve/light-curve-python
  license: GPL-3.0-or-later
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - hombit
