{% set name = "light-curve-python" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/light-curve/light_curve-{{ version }}.tar.gz
  sha256: 70291c5a75e656ffa576b422cc82c07094de3a36873f416d257f52656cb48cf6

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install .[full] -vv --no-deps --ignore-installed
  script_env:
    # Package cargo flags
    - MATURIN_PEP517_ARGS=--locked --no-default-features --features=ceres-system,gsl  # [not win]
    - MATURIN_PEP517_ARGS=--locked --no-default-features  # [win]
    # eigen3 discovery, a transitive dependency of ceres-solver
    - CPLUS_INCLUDE_PATH={{ PREFIX }}/include:{{ PREFIX }}/include/eigen3  # [not win]
    - INCLUDE={{ PREFIX }}\Library\include;{{ PREFIX }}\Library\include\eigen3  # [win]
    # Fix glog-related error when building ceres-solver
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv  # [build_platform != target_platform]
    - maturin >=1,<2  # [build_platform != target_platform]
    - cmake
    - pkg-config
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
    - ceres-solver >=2.2,<2.3  # [not win]
    - gsl >=2.1,<3.0  # [not win]
    - libblas  # [linux]
  run:
    - python
    - numpy <3
    - iminuit >=2.21,<3
    - scipy >=1,<2

test:
  imports:
    - light_curve
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Feature extractor from noisy time series
  home: https://github.com/light-curve/light-curve-python
  license: GPL-3.0-or-later
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - anlava
    - hombit
